---
# tasks file for roles/efs-mount
- include_vars: "{{ aws_account }}.yml"

- name: Install amazon-efs-utils
  yum:
    state: present
    disable_gpg_check: yes
    name:
      - amazon-efs-utils

- name: Mount up /users
  mount:
    path: /users
    src: "{{ user_fs }}:/"
    fstype: efs
    opts:  defaults,_netdev
    state: mounted

- name: Mount up /devel
  mount:
    path: /devel
    src: "{{ devel_fs }}:/"
    fstype: efs
    opts:  defaults,_netdev
    state: mounted
