---
# tasks file for roles/efs-mount
- name: Install amazon-efs-utils
  yum:
    state: present
    disable_gpg_check: yes
    name:
      - amazon-efs-utils

- name: Mount up /users
  mount:
    path: /users
    src: fs-ea567b43:/
    fstype: efs
    opts:  defaults,_netdev
    state: mounted

- name: Mount up /devel
  mount:
    path: /devel
    src: fs-ba87af13:/
    fstype: efs
    opts:  defaults,_netdev
    state: mounted
