---
# tasks file for roles/s3-fuse
- name: Add local repository
  yum_repository:
    name: local
    description: EROS YUM repo
    baseurl: file:///devel/jenkins-rpms-local/x86_64
    gpgcheck: no
    skip_if_unavailable: yes
    priority: 9

- name: Install goofys
  yum: pkg={{item}} state=present update_cache=yes
  with_items:
    - fuse
    - goofys

- name: Mount s3 goofys mounts
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: fuse
    opts:  _netdev,allow_other,--file-mode=0666,ro
    state: mounted
  with_items:
    - { path: /s3/auxiliaries/aster, src: 'goofys#usgs-landsat:/data/auxiliary/aster' }
    - { path: /s3/auxiliaries/L47, src: 'goofys#usgs-landsat:/data/auxiliary/sr/l47' }
    - { path: /s3/auxiliaries/L8 , src: 'goofys#usgs-landsat:/data/auxiliary/sr/l8' }
    - { path: /s3/auxiliaries/NARR, src: 'goofys#usgs-landsat:/data/auxiliary/narr' }
    - { path: /s3/auxiliaries/MODTRAN-DATA, src: 'goofys#usgs-landsat:/data/auxiliary/modtran' }
    - { path: /s3/auxiliaries/landsat, src: 'goofys#usgs-landsat:/data/auxiliary' }
    - { path: /s3/auxiliaries/dem, src:  'goofys#usgs-landsat:/data/auxiliary/dem' }
    - { path: /s3/l0rp, src: 'goofys#usgs-landsat:/data/scene/l0rp/samples' }
