---
# tasks file for roles/s3-fuse
- name: Add local repository
  yum_repository:
    name: local
    description: EROS YUM repo
    baseurl: file:///s3/jenkins-artifacts
    gpgcheck: no
    skip_if_unavailable: yes
    priority: 9

- name: install botocore and boto3
  yum:
    state: present
    name:
      - python2-botocore
      - python2-boto3

#- name: List keys simple
#  aws_s3:
#    bucket: a.out
#    mode: list

- name: Simple GET operation
  aws_s3:
    bucket: a.out
    object: /goofys-master-1.eros.48.x86_64.rpm
    dest: /tmp/goofys-master-1.eros.48.x86_64.rpm
    mode: get

- name: Install goofys
  yum:
    state: present
    name: /tmp/goofys-master-1.eros.48.x86_64.rpm

- name: Install fuse
  yum:
    state: present
    name: fuse

- name: Mount s3 goofys mounts
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: fuse
    opts:  _netdev,allow_other,--file-mode=0666,ro
    state: mounted
  with_items:
    - { path: /s3/auxiliaries/aster, src: 'goofys#usgs-landsat:/data/auxiliary/aster' }
    - { path: /s3/auxiliaries/L47, src: 'goofys#usgs-landsat:/data/auxiliary/sr/l47' }
    - { path: /s3/auxiliaries/L8 , src: 'goofys#usgs-landsat:/data/auxiliary/sr/l8' }
    - { path: /s3/auxiliaries/NARR, src: 'goofys#usgs-landsat:/data/auxiliary/narr' }
    - { path: /s3/auxiliaries/MODTRAN-DATA, src: 'goofys#usgs-landsat:/data/auxiliary/modtran' }
    - { path: /s3/auxiliaries/landsat, src: 'goofys#usgs-landsat:/data/auxiliary' }
    - { path: /s3/auxiliaries/dem, src:  'goofys#usgs-landsat:/data/auxiliary/dem' }
    - { path: /s3/l0rp, src: 'goofys#usgs-landsat:/data/scene/l0rp/samples' }
    - { path: /s3/devel, src: 'goofys#usgs-landsat:/projects/dev' }
    - { path: /s3/jenkins-artifacts, src: 'goofys#usgs-landsat:/jenkins-artifacts' }

- name: Mount up s3 /s3/devel
  mount:
    path: /s3/devel
    src: 'goofys#usgs-landsat:/projects/dev'
    fstype: fuse
    opts: _netdev,allow_other,--file-mode=0666,rw
    state: mounted
