pipeline {
    parameters {
	string(
	    defaultValue: 'Sir-cool',
	    description: 'The name of the user to launch the ec2 instance.',
	    name: 'User')
        booleanParam(defaultValue: false, description: '', name: 'efsmount')
    }
    environment {
	USER = "${params.User}"
    }
    options {
        gitLabConnection('code.usgs.gov')
    }
    triggers {
        gitlab( triggerOnPush: true,
               triggerOnMergeRequest: true,
               branchFilterType: 'NameBasedFilter',
               skipWorkInProgressMergeRequest: true,
               ciSkip: true,
               setBuildDescription: true)
    }
    agent {
	    node {
	        label "ansible"
	    }
    }
    stages {
	    stage('Run EC2 playbook') {
	        steps {
		        script {
		   	        dir('ec2_tools/ansible') {
			            ansiColor('xterm') {
				            ansiblePlaybook(
				                colorized: true,
				                inventory: 'hosts',
    				            credentialsId: 'jenkins-master-key',
	    			            hostKeyChecking: false,
		    		            playbook: 'playbook_ec2.yml',
                                    extraVars: [
                                        efsmount: "${params.efsmount}"
                                    ]
				            )
			            }
			        }
		        }
	        }
	    }
    }
}
