pipeline{
    parameters {
        text(
            defaultValue: 'NamelessDeveloper', 
            description: 'The name of the user to launch the ec2 instance.', 
            name: 'User')
    }
    agent {
        docker {
            image 'cloudformation-builder:latest'
            label 'docker-build-small'
            registryUrl 'https://707566951618.dkr.ecr.us-west-2.amazonaws.com'
            registryCredentialsId 'ecr:us-west-2:jenkins-deploy'
            args "-u root --env USER=${params.User}"
        }
    }
    environment {
        USER = "${params.User}"
    }
    options {
        gitLabConnection('code.usgs.gov')
    }
    triggers {
        gitlab( triggerOnPush: true, 
                triggerOnMergeRequest: true, 
                branchFilterType: 'NameBasedFilter',
                skipWorkInProgressMergeRequest: true,
                ciSkip: true,
                setBuildDescription: true)
    }
    stages {
        stage("Run EC2 playbook"){
            steps {
                script {
                    withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'jenkins-deploy',
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        dir('ec2_tools/ansible') {
                            ansiColor('xterm') {
                                ansiblePlaybook(
                                    inventory: 'hosts',
                                    credentialsId: 'jenkins-master-key',
                                    hostKeyChecking: false,
                                    playbook: 'playbook_ec2.yml')
                            }
                        }
                    }
                }
            }
        }
        stage("Update Hosts File"){
            steps {
                dir('ec2_tools/ansible') {
                    sh('update_hosts_file.sh')
                }
            }
        }
        stage("Run Ansible configuration script"){
            steps {
                script {
                    withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'jenkins-deploy',
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    accessKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        dir('ec2_tools/ansible') {
                            sh 'printenv'
                            ansiColor('xterm') {
                                ansiblePlaybook(
                                    inventory: 'hosts',
                                    credentialsId: 'jenkins-master-key',
                                    hostKeyChecking: false,
                                    playbook: 'playbook_configure_ec2.yml')
                            }                
                        }
                    }
                }
            }
        }
    }
}
