---
- hosts: aws-devel-instance
  remote_user: ec2-user
  vars:
    ansible_ssh_private_key_file: ~/.ssh/djt-us-west-2.pem
  become: yes
  
  roles:
    - efs-mount
    - espa-devel-instance
    

  tasks:
    - name: Add the user 'dtonkin' with a specific uid and a primary group of 'wheel'
      user:
        name: dtonkin
        comment: Dan Tonkin
        uid: 5550
        groups: wheel,docker
        append: yes
        shell: /bin/sh
        home: /devel/dtonkin
        create_home: false
