---
- hosts: aws-devel-instance
  remote_user: ec2-user
  vars:
    ansible_ssh_private_key_file: ~/Dropbox/USGS/daelf-us-west-2.pem
  become: yes
  
  roles:
     - espa-devel-instance

  tasks:
    - name: Add the user 'cattelan' with a specific uid and a primary group of 'wheel'
      user:
        name: cattelan
        comment: Russell Cattelan
        uid: 7000
        groups: wheel,docker
        append: yes
        shell: /bin/sh
        home: /devel/cattelan
        create_home: false
