- name: Create a new EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    region: us-west-2
    instance_type: t2.large
    ami: ami-6cd6f714  # AWS Linux  2
    subnet: subnet-044c596c6b1ad7906
    security_group: sg-0c305038ba5d8d1fb
    username: "{{ lookup('env','USER') }}"
    keypair: jenkins-master # pem file name
    name_tag: "{{ username }}-devel"
    vol_size: 32
    proj_tag: l2pgsv2

  roles:
    - ec2-instance
