- name: Create a new EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    region: us-west-2
    instance_type: <instance-type-t2.large>
    ami: ami-a9d09ed1  # AWS Linux  2
    keypair: <your-keypair-name> # pem file name
    subnet: subnet-d42f6e9c
    ansible_ssh_private_key_file: <~/.ssh/your.pem>
    name_tag: <name-for-the-instance>
    vol_size: 32
    proj_tag: multi-mission
    
  roles:
    - ec2-instance
