- name: Create a new Demo EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    keypair: daelf-us-west-2 # pem file name
    ansible_ssh_private_key_file: ~/Dropbox/USGS/daelf-us-west-2.pem
    vol_size: 32
    name_tag: jenkins-worker
    proj_tag: l2pgsv2
    region: us-west-2
    instance_type: t2.xlarge
    ami: ami-a9d09ed1  # AWS Linux  2
    subnet: subnet-d42f6e9c
    
  roles:
    - ec2-instance
    
  tasks:
    - name: Create SSH Group to login dynamically to EC2 Instance
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: ec2_server
      with_items: "{{ ec2_provision_result.instances }}"

- name: Configure worker
  hosts: ec2_server
  remote_user: ec2-user
  vars:
    ansible_ssh_private_key_file: ~/Dropbox/USGS/daelf-us-west-2.pem
  become: yes
  
  roles:
    - jenkins-docker-worker

- name: Create a new Demo EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    region: us-west-2
    proj_tag: l2pgsv2
    
  tasks:
    - debug: var=ec2_provision_result.instances[0]
      
    - name : Create AMI
      ec2_ami:
        instance_id: "{{ ec2_provision_result.instances[0].id }}"
        wait: yes
        delete_snapshot: yes
        name: jenkins-docker-worker
        tags:
          Name:  jenkins-docker-worker
          Project: "{{ proj_tag }}"

    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        region: "{{ region }}"
        instance_ids: "{{ ec2_provision_result.instances[0].id }}"
