- name: Create a new EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    region: us-west-2
    instance_type: "{{ my_inst_type | default('t2.large') }}"
    username: "{{ lookup('env','USER') }}"
    keypair: "jenkins-master" # pem file name
    name_tag: "{{ username }}-devel"
    vol_size: 32
    proj_tag: l2pgsv2
    ec2build: true
    efsmount: true
  tasks:
  - name: Add override host
    when: override_host is defined
    add_host:
      hostname: "{{ override_host }}"
      groups: ec2_server
    changed_when: false

  roles:
    - { role: 'ec2-instance', when: ec2build }

- name: Configure instance(s)
  hosts: ec2_server
  remote_user: ec2-user
  become: True
  gather_facts: True
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
    - { role: 'efs-mount', when: efsmount }
    - s3-fuse
    - espa-devel-instance

  tasks:
  - include_vars: users.yml

  - name: Add users | create users, shell, home dirs
    user:
      name: '{{ item.username }}'
      shell: /bin/bash
      uid: '{{ item.uid }}'
      createhome: yes
      home: "/users/{{ item.username }}"
      comment: 'create with ansible'
      groups: docker
      append: yes
    with_items: '{{users}}'

  - name: Setup | authorized key upload
    authorized_key:
      user: "{{ item.username }}"
      key: "{{ lookup('file', 'pub_keys/{{ item.username }}.pub') }}"
    with_items: '{{users}}'

  - name: sudoers | update sudoers file and validate
    lineinfile: "dest=/etc/sudoers
    insertafter=EOF
    line='{{ item.username }} ALL=(ALL) NOPASSWD: ALL'
    regexp='^{{ item.username }} .*'
    state=present"
    when: item.use_sudo
    with_items: '{{users}}'
