---
users:
  - username: cattelan
    use_sudo: yes
    uid: 7000

  - username: jzubke
    use_sudo: yes
    uid: 7777

  - username: jcavanaugh
    use_sudo: yes
    uid: 7010

  - username: epost
    use_sudo: yes
    uid: 7575

  - username: sshrestha
    use_sudo: yes
    uid: 7272

  - username: tluell
    use_sudo: yes
    uid: 7100

  - username: sgould
    use_sudo: yes
    uid: 7070

  - username: wchowlin
    use_sudo: yes
    uid: 7071

  - username: rhoffman
    use_sudo: yes
    uid: 7111

  - username: whowe
    use_sudo: yes
    uid: 7654

  - username: dbuswell
    use_sudo: yes
    uid: 3044

