---
# tasks file for jenkin-docker-worker

# Include variables based off of account name passed to playbook via --extra-vars "aws_account=chs"
- include_vars: "{{ aws_account | default('chs') }}.yml"

##-- Repo Setup --##
- name:  Add the epel repo
  yum:
    lock_timeout: 180
    name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm'
    state: present

- name:  Add the IUS repo
  yum:
    lock_timeout: 180
    name: 'https://centos7.iuscommunity.org/ius-release.rpm'
    state: present

- name: Enable the Amazon Linux Extras Docker Repo
  command: "amazon-linux-extras enable docker"

##-- Local S3 Repo Setup --##
- name: Add local repository
  yum_repository:
    name: local
    description: EROS YUM repo
    baseurl: file:///s3/jenkins-artifacts
    gpgcheck: no
    skip_if_unavailable: yes
    priority: 9

- name: install botocore and boto3
  yum:
    lock_timeout: 180
    state: present
    name:
      - python2-botocore
      - python2-boto3

- name: Simple GET operation
  aws_s3:
    bucket: usgs-landsat-too
    object: "junkbox/goofys-master-1.eros.x86_64.rpm"
    dest: /tmp/goofys-master-1.eros.x86_64.rpm
    mode: get

- name: Install goofys
  yum:
    lock_timeout: 180
    state: present
    name: /tmp/goofys-master-1.eros.x86_64.rpm

- name: Install fuse
  yum:
    lock_timeout: 180
    state: present
    name: fuse

- name: Mount s3 goofys mounts
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: fuse
    opts:  _netdev,allow_other,--file-mode=0666,ro
    state: mounted
  with_items:
    - { path: /s3/jenkins-artifacts, src: 'goofys#{{ s3_bucket }}:/jenkins-artifacts' }

- name: Install Amazon ECR Credential Helper
  yum:
    lock_timeout: 180
    name: "amazon-ecr-credential-helper"
    state: present
 
- name: Install nfs-utils
  yum:
    lock_timeout: 180
    name: nfs-utils
    state: present

- name: Install java-1.8.0-openjdk
  package:
    lock_timeout: 180
    name: java-1.8.0-openjdk
    state: present

- name: Update all packages to latest
  yum:
    lock_timeout: 180
    name: '*'
    state: latest

- name: Install specific mock package for centos 7
  yum:
    lock_timeout: 180
    name:
      - mock
      - rpm-build
      - createrepo
      - createrepo_c
      - git2u
      - git-lfs
      - docker
      - awscli
    state: present

- name: enable service nfs and ensure it is not masked
  systemd:
    name: nfs
    enabled: yes
    state: started
    masked: no

- name: enable service docker and ensure it is not masked
  systemd:
    name: docker
    enabled: yes
    state: started
    masked: no

- name: adding existing user ec2-user to group docker
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: Create docker dir for ECR credential helper
  file:
    path: "/home/ec2-user/.docker"
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: 0700

- name: Deploy config.json for ECR credential helper
  copy:
    src: "docker-ecr-cred-helper-config.json"
    dest: "/home/ec2-user/.docker/config.json"
    owner: ec2-user
    group: ec2-user
    mode: 0600

