---
# tasks file for ec2-instance
- include_vars: "{{ aws_account }}.yml"

- name: Create an ec2 instance
  ec2:
    key_name: "{{ keypair }}"
    groups: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami }}"
    wait: true
    instance_profile_name: "{{ profile_name }}"
    region: "{{ region }}"
    count: 1  # default
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: "{{ vol_size}}"
        delete_on_termination: yes
        tags:
          - Project: "{{ proj_tag }}"
    count_tag:
      Name: "{{ name_tag }}"
      Project: "{{ proj_tag }}"
    instance_tags:
      Name: "{{ name_tag }}"
      Project: "{{ proj_tag }}"
    vpc_subnet_id: "{{ subnet }}"
    assign_public_ip: no
    instance_initiated_shutdown_behavior: terminate
    spot_price: 0.24
    spot_type: one-time
  register: ec2_provision_result

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.private_ip }}"
    port: 22
    state: started
  with_items: "{{ ec2_provision_result.instances }}"

#- debug:
#    var: ec2_provision_result
#- debug:
#    var: ec2_provision_result.instances
- debug:
    var: ec2_provision_result.instances[0].public_ip
- debug:
    var: ec2_provision_result.instances[0].private_ip

- name: Create SSH Group to login dynamically to EC2 Instance
  add_host:
    hostname: "{{ item.private_ip }}"
    groups:
      - ec2_server
      - jenkins_server
  with_items: "{{ ec2_provision_result.instances }}"
