---
# tasks file for ec2-instance

- name: Create an ec2 instance
  ec2:
    key_name: "{{ keypair }}"
    group: daelf-default # security group name
    instance_type: "{{ instance_type}}"
    image: "{{ ami }}"
    wait: true
    region: "{{ region }}"
    count: 1  # default
    count_tag:
      Name: "{{ my_tag }}"
    instance_tags:
       Name: "{{ my_tag }}"
    vpc_subnet_id: "{{ subnet }}"
    assign_public_ip: true
    spot_price: 0.24
    
  register: ec2_provision_result

#- debug: var: ec2_provision_result
#- debug: var=ec2_provision_result.instances

- name: Wait for SSH to come up
  local_action: wait_for
  host: "{{ item.public_ip }}"
  port: 22
  state: started
  with_items: "{{ ec2_provision_result.instances }}"

- debug: var=ec2_provision_result.instances[0].public_ip

- name: Create SSH Group to login dynamically to EC2 Instance
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: ec2_server
  with_items: "{{ ec2_provision_result.instances }}"
