---
- hosts: espa-process
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Update all packages to latest
      yum: name=* state=latest

    - name: Install zsh
      yum: name=zsh state=present

    - name: Install amazon-efs-utils
      yum: name=amazon-efs-utils state=present

    - name: Install ecs-init
      yum: name=ecs-init state=present

    - name: Install fuse
      yum: name=fuse state=present

    - name: Install docker
      yum: name=docker state=present

    - name: Install nginx
      yum: name=nginx state=present

    - name: Creates directory /efs
      file: path=/efs state=directory
    - name: Creates directory /devel
      file: path=/devel state=directory
    - name: Creates directory /jobtmp
      file: path=/jobtmpl state=directory  mode=0777

    - name: Mount up /efs
      mount:
        path: /efs
        src: fs-174024be:/
        fstype: efs
        opts:  defaults,_netdev
        state: present

    - name: Mount up /devel
      mount:
        path: /devel
        src: fs-15a9c8bc:/
        fstype: efs
        opts:  defaults,_netdev
        state: present

    - name: adding existing user ec2-user to group sudo
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Add the user 'cattelan' with a specific uid and a primary group of 'wheel'
      user:
        name: cattelan
        comment: Russell Cattelan
        uid: 7000
        group: wheel
        shell: /bin/zsh
        home: /efs/cattelan
        create_home: false
