---
- name:  Add the epel repo
  yum: name='https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm' state=present

- name: Install amazon-efs-utils
  yum: name=amazon-efs-utils,python-boto3,tmux state=present

- name: Creates directory /devel
  file: path=/devel state=directory

- name: Mount up /devel
  mount:
    path: /devel
    src: fs-ea567b43:/
    fstype: efs
    opts:  defaults,_netdev
    state: mounted

- name: Add local repository
  yum_repository:
    name: local
    description: EROS YUM repo
    baseurl: file:///devel/jenkins-rpms-local/x86_64
    gpgcheck: no
    skip_if_unavailable: yes

- name: Add oracle repository
  yum_repository:
    name: oracle-client
    description: Oracle client rpm repo
    baseurl: file:///devel/oracle-rpms-repo/x86_64
    gpgcheck: no
    skip_if_unavailable: yes

- name: Update all packages to latest
  yum: name=* state=latest

- name: Install specific mock package for centos 7
  yum: name=mock,rpm-build,createrepo,createrepo_c state=present

- name: Install git
  yum: name=git,git-lfs state=present

- name: Install zsh
  yum: name=zsh state=present

- name: Install ESPA python lib
  yum: pkg={{item}} state=present disable_gpg_check=yes update_cache=yes
  with_items:
    - python-espa
    - python-watchtower

- name: Install jq
  yum: name=jq state=present

- name: Install fuse
  yum: name=fuse state=present

- name: Install docker
  yum: name=docker state=present

- name: adding existing user ec2-user to group sudo
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: enable service nfs and ensure it is not masked
  systemd:
    name: nfs
    enabled: yes
    state: started
    masked: no

- name: enable service docker and ensure it is not masked
  systemd:
    name: docker
    enabled: yes
    state: started
    masked: no

- name: adding existing user ec2-user to group sudo
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- copy: src=files/etc/ld.so.conf.d/oracle-x86_64.conf dest=/etc/ld.so.conf.d/oracle-x86_64.conf

- name: Update ldconfig
  command: ldconfig

- name: Oracle rpms
  yum: pkg={{item}} state=present disable_gpg_check=yes update_cache=yes
  with_items:
    - oracle-instantclient12.2-jdbc
    - oracle-instantclient12.2-sqlplus
    - oracle-instantclient12.2-devel
    - oracle-instantclient12.2-basic
    - oracle-instantclient12.2-odbc
    - oracle-instantclient12.2-tools
    - perl-DBD-Oracle
