---
# tasks file for ephemeral
- name: install sysv ephmeral
  copy: src=files/ephemeral dest=/etc/init.d/ephemeral owner=root group=root mode=0755

- name: make sure ephemeral starts at boot
  sysvinit:
    name: ephemeral
    state: started
    enabled: yes
    state: mounted

- name: Set permissions to open on /jobtmp
  file:
    path: "/jobtmp"
    mode: 0777

