---
- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: us-west-2
      instance_type: t2.small
      ami: ami-28e07e50 # RedHat 7.5
      keypair: daelf-us-west-2 # pem file name

  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: daelf-default # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: Jenkins-RHEL-worker
         instance_tags:
            Name: Jenkins-RHEL-worker
         vpc_subnet_id: subnet-1c2b6a54
         assign_public_ip: true
      register: ec2

    - name: Wait for SSH to come up
      local_action: wait_for
      host: "{{ item.public_ip }}"
      port: 22
      state: started
      with_items: ec2.instances
