---
- hosts: jenkins-rpm-build
  remote_user: ec2-user
  vars:
    ansible_ssh_private_key_file: ~/Dropbox/USGS/daelf-us-west-2.pem
  become: yes
  pre_tasks:
    - set_fact: ansible_distribution_major_version=7
      when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "NA"

  tasks:
    - name: Install nfs-utils
      yum: name=nfs-utils state=present

    - name: Install java-1.8.0-openjdk
      yum: name=java-1.8.0-openjdk state=present

    - name: Creates directory /devel
      file: path=/devel state=directory

    - name: Mount up /devel
      mount:
        path: /devel
        src: fs-15a9c8bc.efs.us-west-2.amazonaws.com:/ 
        fstype: nfs4
        opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 
        state: mounted

    - name: Update all packages to latest
      yum: name=* state=latest

    - name:  Add the epel repo
      yum: name='https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm' state=present

    - name:  Add the IUS repo
      yum: name='https://centos7.iuscommunity.org/ius-release.rpm' state=present

    - name: Install specific mock package for centos 7
      yum: name=mock,rpm-build,createrepo state=present

    - name: Install git
      yum: name=git2u,git-lfs state=present

    - name: enable service nfs and ensure it is not masked
      systemd:
        name: nfs
        enabled: yes
        state: started
        masked: no
