pipeline{
    agent {
        docker {
            image 'cloudformation-builder:latest'
            label 'docker-build-small'
            registryUrl 'https://707566951618.dkr.ecr.us-west-2.amazonaws.com'
            registryCredentialsId 'ecr:us-west-2:jenkins-deploy'
            args '-u root'
        }
    }
    options {
        gitLabConnection('code.usgs.gov')
    }
    triggers {
        gitlab( triggerOnPush: true, 
                triggerOnMergeRequest: true, 
                branchFilterType: 'NameBasedFilter',
                skipWorkInProgressMergeRequest: true,
                ciSkip: true,
                setBuildDescription: true)
    }
    stages {
        stage("Run ansible provisioning script"){
            steps { 
                ansiblePlaybook('ec2_tools/ansible/playbook_espa_ips_ami.yml') {
                    ansibleName('2.5.0')
                }
            }
        }
    }
}
